version: '3.4'

services:
  node:
    image: ${DOCKER_REGISTRY-}cscdn-ma
    build:
      context: .
      dockerfile: CSCDN-MA/Dockerfile
    expose:
      - "80"
    environment:
      - ENVIRONMENT=production
      - ASPNETCORE_ENVIRONMENT=Production
      - "CONNECTION_STRING=Data Source=<Server Address>;Initial Catalog=<Database>;Persist Security Info=True;User ID=<userid (DO NOT USE `sa` user)>;Password=<password>"
    volumes:
      - ./data:/data
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    ports:
      - "<port>:4000"
networks:
  default:
    driver: bridge
    name: czsoftcdn